---
title: "20230130-vc_abundance"
title-block-banner: true
author:
  - name: Jinlong Ru
    orcid: 0000-0002-6757-6018
    email: jinlong.ru@gmail.com
    affiliations:
      - name: Institute of Virology, Helmholtz Centre Munich – German Research Center for Environmental Health, 85764 Neuherberg, Germany
      - neme: Chair of Prevention of Microbial Diseases, School of Life Sciences Weihenstephan, Technical University of Munich, 85354 Freising, Germany
date: 2022-11-06
toc: true
format: gfm
bibliography: refs.bib
params:
  name: "20230130-vc_abundance" # change if you rename file
---

Updated: `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'CET')` CET.

```{r setup, message=FALSE, include=F}
# uuid::UUIDgenerate()
here::i_am(paste0(params$name, ".qmd"), uuid = "7301e970-2007-454b-ab3a-e1a557c1b610")
projthis::proj_create_dir_target(params$name, clean = F)
path_target <- projthis::proj_path_target(params$name)
path_source <- projthis::proj_path_source(params$name)
```

## Tasks

```{r}
library(here)
library(tidyverse)
library(ggrepel)
library(p0064gvhd)
library(vpfutils)
```

```{r}
prj_path <- normalizePath("..")
dpath <- here(prj_path, "hpc/hms/virmerge/phamb/results")
fin_vc2 <- here(dpath, "genome_by_genome_overview.csv")
fin_ab_covfrac <- here(dpath, "abundance_contigs_covered_fraction.tsv")
fin_ab_count <- here(dpath, "abundance_contigs_count.tsv")
fin_ab_tpm <- here(dpath, "abundance_contigs_tpm.tsv")
mincov <- 0.1

vc2 <- read_vcontact2(fin_vc2, assembler_label = "__")
dfab_count <- read_coverm(fin_ab_count)
dfab_covfrac <- read_coverm(fin_ab_covfrac)

df_ctg2vc <- vc2$vc_tbl %>% 
  dplyr::mutate(genome_id = virsorter2_contig_id) %>% 
  dplyr::select(c("genome_id", "vConTACT_VC2"))

dfab_tpm <- read_coverm(fin_ab_tpm) %>% 
  left_join(df_ctg2vc, by = "genome_id") %>%
  dplyr::mutate(genome_id = ifelse(is.na(vConTACT_VC2), genome_id, vConTACT_VC2)) %>%
  dplyr::select(-vConTACT_VC2) %>%
  dplyr::group_by(genome_id) %>%
  dplyr::summarise_all(sum) %>% 
  column_to_rownames("genome_id") %>% 
  as.matrix()

dfab_covfrac <- read_coverm(fin_ab_covfrac, "cov") %>% 
  left_join(df_ctg2vc, by = "genome_id") %>% 
  dplyr::mutate(genome_id = ifelse(is.na(vConTACT_VC2), genome_id, vConTACT_VC2)) %>%
  dplyr::select(-vConTACT_VC2) %>% 
  dplyr::group_by(genome_id) %>% 
  dplyr::summarise_all(max) %>% 
  column_to_rownames("genome_id") %>% 
  mutate_at(vars(everything()), ~ ifelse(. < mincov, 0, 1)) %>%
  as.matrix()

df_tpm_normby_covfrac <- dfab_covfrac[rownames(dfab_tpm), colnames(dfab_tpm)] * dfab_tpm %>%
  as.data.frame() %>% 
  dplyr::mutate(across(everything(), replace_na, 0)) %>% 
  dplyr::mutate_at(vars(everything()), ~ . / sum(.) * 100) %>%
  dplyr::mutate_at(vars(everything()), ~ round(., 8))

rst <- df_tpm_normby_covfrac %>% 
  rownames_to_column("genome_id") %>% 
  dplyr::filter(genome_id %in% c("27_1", "62_0", "BAC3_V__5269"))

openxlsx::write.xlsx(rst, file = path_target("tpm_3genomes_relab.xlsx"))
```



## Files written

These files have been written to the target directory, ```r paste0("data/", params$name)```:

```{r list-files-target}
projthis::proj_dir_info(path_target())
```

