---
title: "Correlation analyses"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(readxl)
source(here("scripts/scripts.R"))

# load(here("data/processed/pseq_16s.RData"))
# load(here("data/processed/pseq_vir.RData"))
# virome <- read_excel(here("data/collab/virmerge-old/result/abundance/AbundPervmerge1.xlsx"))


pseq_16s <- tax_glom(pseq_16s, taxrank = "Genus", NArm = FALSE)

sel_bacteria_bad <- c("Enterococcus", "Streptococcus", "Staphylococcus", "Klebsiella", "Lactobacillus", "Escherichia", "Prevotella", "Stenotrophomonas")
sel_bacteria_good <- c("Lachnospiraceae", "Blautia", "Sellimonas", "Anaerostipes", "Ruminococcaceae", "Flavinofractor", "Bacteroidetes", "Prevotella", "Barnesiella", "Actinobacteria", "Bifidobacterium", "Actinomyces", "Erysipelotrichaceae")
sel_bacteria <- c(sel_bacteria_bad, sel_bacteria_good)

pseq_16s_sel <- subset_taxa(pseq_16s, Genus %in% sel_bacteria)

otu_good <- pseq_16s_sel@tax_table@.Data %>% 
  as.data.frame() %>% 
  filter(Genus %in% sel_bacteria_good) %>% 
  dplyr::select(Genus)

otu_bad <- pseq_16s_sel@tax_table@.Data %>% 
  as.data.frame() %>% 
  filter(Genus %in% sel_bacteria_bad) %>% 
  dplyr::select(Genus)

# clr_vir = pseq_vir@otu_table@.Data %>% 
#   as.data.frame() %>% 
#   filter(rownames(.) %in% c(QC, QH)) %>% 
#   filter(rowSums(.==0)<0.8*ncol(.)) %>% 
#   filter(rowSums(.)>100) %>% 
#   clr_trans(metadata, 1)
# clr_16s = pseq_16s@otu_table@.Data %>% 
#   as.data.frame() %>% 
#   filter(rowSums(.)>100) %>% 
#   clr_trans(metadata, 1)
# clr_ITS = pseq_ITS@otu_table@.Data %>% 
#   as.data.frame() %>% 
#   filter(rowSums(.)>100) %>% 
#   clr_trans(metadata, 1)


# multidata <- list("virome"=clr_vir, 
#                   "16S"=clr_16s, 
#                   "ITS"= clr_ITS)
                  # "bile_acids"=mtb_BileAcid,
                  # "SCFA"=mtb_SCFA)
```


```{r}
bac <- MOFAobject@data$`16S`$group1
vir <- MOFAobject@data$virome$group1
bac_sel <- bac %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  filter(rowname %in% rownames(pseq_16s_sel@otu_table)) %>% 
  column_to_rownames("rowname")


b2v <- psych::corr.test(t(vir), t(bac_sel))
b2v.cor <- b2v$r
b2v.cor[is.na(b2v.cor)]  <- 0
b2v.cor.sel <- b2v.cor[rowSums(abs(b2v.cor)>0.6)>0,]
dim(b2v.cor.sel)

pheatmap::pheatmap(b2v.cor.sel, 
                   show_rownames=T,
                   show_colnames = T,
                   fontsize = 8)
```
```{r}
otu_bad
```

