---
title: "MOFA analyses"
author: "Jinlong Ru"
date: '2021-11-30'
output:
  html_document:
    df_print: paged
  html_notebook: default
---

Create phyloseq object by running `create_phyloseq_objects.R`.

```{r load datasets, message=FALSE, warning=FALSE}
library(here)
library(MOFA2)
library(readxl)
source(here("scripts/scripts.R"))
fpath_metadata = here("data/processed/metadata.tsv")
fpath_metabolites_BileAcid <- here("data/collab/2021-12-08_metabolites_email/MRI + UKR Bile acid dry feces_normalized.xlsx")
fpath_metabolites_SCFA <- here("data/collab/2021-12-08_metabolites_email/MRI + UKR SCFA dry feces_normalized.xlsx")
samples_donor <- c("R-AA-0", "R-AG-0", "R-AL-0", "R-BA-0", "R-BD-0")
# sample_outlier <- c("M-AA-1", "M-AA-2", "M-AA-3", "M-AA-4", "M-AA-5")
# samples_donor <- c(samples_donor, sample_outlier)

mtb_BileAcid <- read_excel(fpath_metabolites_BileAcid) %>% 
  dplyr::select(-c("1","2"))
  # column_to_rownames('sample') %>% 
  # t() %>% 
  # as.data.frame()
  # read_metabolites(metadata)
colnames(mtb_BileAcid) <- make.names(colnames(mtb_BileAcid))
mtb_SCFA <- read_excel(fpath_metabolites_SCFA) %>% 
  dplyr::select(-c("1","2"))
  # column_to_rownames('sample') %>% 
  # t() %>% 
  # as.data.frame()
  # read_metabolites(metadata)
colnames(mtb_SCFA) <- make.names(colnames(mtb_SCFA))

bileAcid <- colnames(mtb_BileAcid)[-1]
SCFA <- colnames(mtb_SCFA)[-1]

metadata_raw <- read_tsv(fpath_metadata)
metadata <- metadata_raw %>% 
  filter(!Project_ID %in% samples_donor) %>% 
  filter(!str_detect(Project_ID, "M-AY")) %>% 
  drop_na(survival1year) %>%
  arrange(Project_ID) %>% 
  mutate(sample=Project_ID) %>% 
  mutate(survival1year=replace_na(survival1year, -1)) %>% 
  left_join(mtb_BileAcid, by = "sample") %>% 
  left_join(mtb_SCFA, by = "sample")

load(here("data/processed/pseq_16s.RData"))
load(here("data/processed/pseq_ITS.RData"))
load(here("data/processed/pseq_vir.RData"))
nrow(pseq_vir@otu_table@.Data)


# phamb
dir_phamb <- here("data/hms/virmerge/phamb/results/")
checkv <- fread(here(dir_phamb, "quality_summary.tsv"))
vc <- fread(here(dir_phamb, "genome_by_genome_overview.csv"), drop = 1)
colnames(vc) <- make.names(colnames(vc))
vc_clusters <- vc %>% 
  mutate(contig_id=Genome) %>% 
  dplyr::select(c("contig_id", "VC.Subcluster")) %>% 
  filter(str_detect(contig_id, "__"))

vOTU <- fread(here(dir_phamb, "vOTUs.tsv"))  %>% 
  mutate(contig_id=repid) %>% 
  select(contig_id) %>% 
  distinct(contig_id) %>% 
  left_join(checkv, by="contig_id") %>% 
  left_join(vc_clusters, by = "contig_id") %>% 
  mutate(VC.Subcluster=ifelse(VC.Subcluster=="", contig_id, VC.Subcluster))

QC <- extract_vc_by_quality(vOTU, "Complete")
QH <- extract_vc_by_quality(vOTU, "High-quality")
QI <- extract_vc_by_quality(vOTU, "Medium-quality")
QL <- extract_vc_by_quality(vOTU, "Low-quality")
QU <- extract_vc_by_quality(vOTU, "Not-determined")
```


```{r Prepare input for MOFA2, message=FALSE, warning=FALSE}
clr_vir = pseq_vir@otu_table@.Data %>% 
  as.data.frame() %>% 
  filter(rownames(.) %in% c(QC, QH)) %>% 
  # rename_at(vars(metadata_vir$sample_id_virome), ~metadata_vir$SampleName) %>%
  filter(rowSums(.<50)<0.9*ncol(.)) %>% 
  clr_trans(metadata, 1)
clr_16s = pseq_16s@otu_table@.Data %>% 
  as.data.frame() %>% 
  # rename_at(vars(metadata_16s$sample_id_16s), ~metadata_16s$SampleName) %>% 
  filter(rowSums(.)>100) %>% 
  clr_trans(metadata, 1)
clr_ITS = pseq_ITS@otu_table@.Data %>% 
  as.data.frame() %>% 
  # rename_at(vars(metadata_18s$sample_id_18s), ~metadata_18s$SampleName) %>% 
  filter(rowSums(.)>100) %>% 
  clr_trans(metadata, 1)


multidata <- list("virome"=clr_vir, 
                  "16S"=clr_16s, 
                  "ITS"= clr_ITS)
                  # "bile_acids"=mtb_BileAcid,
                  # "SCFA"=mtb_SCFA)
nrow(clr_vir)
```


```{r MOFA}
nfactors <- 10
# Group: survival1yeara
fmodel_name <- paste0("group-survival_nfactors-", nfactors)
MOFAobject <- create_mofa(multidata, groups = metadata$survival1year)
samples_metadata(MOFAobject) <- metadata %>% 
   mutate(group=survival1year)


# Group: GvHD
fmodel_name <- paste0("group-GvHD_nfactors-", nfactors)
MOFAobject <- create_mofa(multidata, groups = metadata$GvHD)
samples_metadata(MOFAobject) <- metadata %>%
   mutate(group=GvHD)
# # #
# # Group: no
fmodel_name <- paste0("group-no_nfactors-", nfactors)
MOFAobject <- create_mofa(multidata)
samples_metadata(MOFAobject) <- metadata

data_opts <- get_default_data_options(MOFAobject)
model_opts <- get_default_model_options(MOFAobject)
train_opts <- get_default_training_options(MOFAobject)
train_opts$convergence_mode <- "slow"
train_opts$seed <- 42
model_opts$num_factors <- nfactors

MOFAobject <- prepare_mofa(
  MOFAobject, 
  data_options = data_opts,
  training_options = train_opts,
  model_options = model_opts
)

# -------- Run MOFA2 --------
MOFAobject <- run_mofa(MOFAobject, outfile = here("results", paste0("MOFA_model_", fmodel_name, "_nfactors-",as.character(nfactors), ".hdf5")))
# plt_cum_var(MOFAobject, here("figs", paste0("cum-var_", fmodel_name, ".pdf")))
plot_variance_explained(MOFAobject, plot_total = TRUE)
ggsave(here("figs", paste0("variance-explained_", fmodel_name, ".pdf")))
plot_data_overview(MOFAobject)
ggsave(here("figs", paste0("data-overview_", fmodel_name, ".pdf")))
save(MOFAobject, file=here("data/processed/MOFAobject.RData"))
```

```{r Correlate with metabolites}
correlate_factors_with_covariates(MOFAobject,
                                  covariates = SCFA,
                                  plot = 'r')

correlate_factors_with_covariates(MOFAobject,
                                  covariates = bileAcid,
                                  plot = 'r')

correlate_factors_with_covariates(MOFAobject,
                                  covariates = bileAcid,
                                  plot = 'log_pval')

plot_factors(MOFAobject,
             factors = c(1,2),
             color_by = "Valeric.acid",
             # color_by = "survival1year",
             # color_by = "GvHD",
             dot_size = 2) +
  scale_fill_gradient(low = "white", high = "#BF3EFF")

plot_factor(MOFAobject, 
            factors = 1:5,
            color_by = "GvHD",
            dodge=T,
            add_violin = T,
            add_boxplot = T,
            stroke = 0.5,
            dot_size = 2)

plot_weights(MOFAobject,
             factors = 2,
             view = "virome",
             nfeatures = 10)

plot_top_weights(MOFAobject,
                 view = "16S",
                 factors = 1,
                 nfeatures = 10)

plot_weights_heatmap(MOFAobject,
                     view = "16S")

plot_weights_scatter(MOFAobject,
                     view = "ITS",
                     factors = c(1,2))

plot_data_heatmap(MOFAobject,
                  factor = 1,
                  view = "ITS",
                  features = 5,
                  scale = "row",
                  denoise = T
                  )

plot_data_scatter(MOFAobject,
                  factor = 3,
                  view = "16S",
                  features = 2)

colnames(metadata)

typeof(MOFAobject)

# 2021-01-15: send 5 ITS figure to Jinling
for (f in c(1,3,4,5, 6)) {
  plt <- plot_top_weights(MOFAobject,
                   view = "ITS",
                   factors = f,
                   nfeatures = 10)
}
```

```{r}
SCFA
```



Downstream analyses can be done in [shinny](https://github.com/gtca/mofaplus-shiny).

```{r MOFA2 downstream analyses}
plot_data_overview(MOFAobject)
ggsave(here("figs/data_overview.pdf"))
plot_factor_cor(MOFAobject)

plot_factors(MOFAobject, factors = c(1,2),
                  dot_size = 4, color_by = "GvHD") +
    stat_ellipse(geom = "polygon", alpha=0.25, ) +
    geom_text(aes(label=sample),hjust=0, vjust=0, label.size=0.1)
```

# Correlation

```{r}
pseq_16s_genus <- tax_glom(pseq_16s, taxrank = "Genus", NArm = FALSE)

sel_bacteria_bad <- c("Enterococcus", "Streptococcus", "Staphylococcus", "Klebsiella", "Lactobacillus", "Escherichia", "Prevotella", "Stenotrophomonas")
sel_bacteria_good <- c("Lachnospiraceae", "Blautia", "Sellimonas", "Anaerostipes", "Ruminococcaceae", "Flavinofractor", "Bacteroidetes", "Prevotella", "Barnesiella", "Actinobacteria", "Bifidobacterium", "Actinomyces", "Erysipelotrichaceae")
sel_bacteria <- c(sel_bacteria_bad, sel_bacteria_good)

pseq_16s_sel <- subset_taxa(pseq_16s_genus, Genus %in% sel_bacteria)

otu_good <- pseq_16s_sel@tax_table@.Data %>% 
  as.data.frame() %>% 
  filter(Genus %in% sel_bacteria_good) %>% 
  dplyr::select(Genus)

otu_bad <- pseq_16s_sel@tax_table@.Data %>% 
  as.data.frame() %>% 
  filter(Genus %in% sel_bacteria_bad) %>% 
  dplyr::select(Genus)

# --------- correlation -----------
bac <- MOFAobject@data$`16S`$group1
vir <- MOFAobject@data$virome$group1
bac_sel <- bac %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  filter(rowname %in% rownames(pseq_16s_sel@otu_table)) %>% 
  column_to_rownames("rowname")

b2v <- psych::corr.test(t(vir), t(bac_sel))
b2v.cor <- b2v$r
b2v.cor[is.na(b2v.cor)]  <- 0
b2v.cor.sel <- b2v.cor[rowSums(abs(b2v.cor)>0.55)>0,]

otu_genus <- pseq_16s_genus@tax_table@.Data %>% 
  as.data.frame() %>% 
  dplyr::select(Genus) %>% 
  filter(rownames(.) %in% colnames(b2v.cor.sel))

b2v.cor.sel %>% 
  as.data.frame() %>% 
  rename(set_names(rownames(otu_genus), otu_genus$Genus)) %>% 
  pheatmap::pheatmap(show_rownames=T,
                   show_colnames = T,
                   fontsize = 8)
```

