---
title: "R Notebook"
output: html_notebook
---

```{r}
library(here)
library(tidyverse)
library(treedataverse)
library(pals)

dpath <- here("~/project/tmp/20220718_BCoAT/")
ftree <- here(dpath, "tree.nwk")
ffaa <- here(dpath, "MSAtrimmed_onlyID.faa")
fanno <- here(dpath, "nf_tmp_prot2taxa.tsv")
fanno_name2taxid <- here(dpath, "nf_tmp_name2taxid.tsv")
fanno_taxid2lineage <- here(dpath, "nf_tmp_taxaid2lineage.tsv")

# Annotation
df_name2taxid <- read.csv(fanno_name2taxid, sep = "\t", header = F, col.names = c("taxname", "taxid"))
df_taxid2lineage <- read.csv(fanno_taxid2lineage, sep = "\t")
df_anno <- read.csv(fanno, sep = "\t", col.names = c("label", "taxname"), header = F) %>% 
  left_join(df_name2taxid, by = "taxname") %>% 
  left_join(df_taxid2lineage, by = "taxid") %>% 
  mutate(refs=ifelse(taxname %in% c("BAF3", "BAM6"), 1, 0)) %>% 
  mutate(Species = ifelse(is.na(Species), taxname, Species)) %>% 
  mutate(Superkingdom = ifelse(refs==1, "Viruses", Superkingdom)) %>% 
  replace(is.na(.), "") %>% 
  mutate(Superkingdom=paste0("k__", Superkingdom)) %>% 
  mutate(Phylum=paste0("p__", Phylum)) %>% 
  mutate(Class=paste0("c__", Class)) %>% 
  mutate(Order=paste0("o__", Order)) %>% 
  mutate(Family=paste0("f__", Family)) %>% 
  mutate(Genus=paste0("g__", Genus)) %>%
  # mutate(Species=paste0("s__", Species)) %>% 
  mutate(Taxonomy=paste(Superkingdom, Phylum, Class, Order, Family, sep = ";"))


colval <- c("#2f4f4f", "#2e8b57", "#800000", "#808000", "#00008b", "#ff4500", "#ffa500", "#ffff00", "#c71585", "#00ff00", "#00fa9a", "#00ffff", "#00bfff", "#9370db", "#0000ff", "#d8bfd8", "#ff00ff", "#eee8aa", "#ffa07a")
names(colval) = sort(unique(df_anno$Taxonomy))

# Tree
tree <- read.tree(ftree) %>% 
  as_tibble() %>% 
  left_join(df_anno, by = "label") %>% 
  as.treedata()

save_tree <- function(tree, colval, fout, tiplab_size=1, tippoint_size=1.5, legeng_x=1.2, scale=0.75) {
  # p <- ggtree(tree, aes(color=as.factor(refs)), layout = "fan", branch.length="none") +
  p <- ggtree(tree, layout = "fan", color="grey") +
    # geom_tiplab(aes(label=Species), size=1, align=TRUE, linesize=.2, hjust=0) +
    # geom_tiplab(aes(label=Species), size=1, align=TRUE, linesize=.2, hjust=0) +
    geom_tiplab2(aes(subset=(refs!=1), label=Species), size=tiplab_size, align=T, linesize=0.1, hjust = 0) +
    geom_tiplab2(aes(subset=(Superkingdom=="k__Viruses"), label=Species), size=tiplab_size, color="red", align=T, linesize=0.3, hjust = 0) +
    # scale_color_manual(values = c("black", "red"), guide="none") +
    geom_tippoint(aes(color=Taxonomy), alpha=0.7, size=tippoint_size) +
    scale_color_manual(values = colval) +
    # ggnewscale::new_scale_fill() +
    # geom_hilight(ggtree(tree)$data,
    #              mapping = aes(node=node, fill=as.factor(Family)), alpha=0.3) +
    theme_tree(legend.position = c(legeng_x, 0.5))
  
  p2 <- p + geom_point2(aes(subset=(Superkingdom=="k__Viruses")), size=5, alpha=0.3, color="red")
  p3 <- ggplotify::as.ggplot(p2, angle=0, scale=scale)
  ggsave(p3, filename = fout, width = 22, height = 16)
  return(p2)
}

tree_vis <- save_tree(tree, colval, "tree_BCoAT.pdf", scale = 0.8, legeng_x = 1.3)
tree_vis <- save_tree(tree, colval, "tree_BCoAT.svg", scale = 0.8, legeng_x = 1.3)
```

```{r Save sub-tree}
LCA_node <- MRCA(t1, c(df_anno[df_anno$refs==1,][["label"]]))

tree_sub <- tree_vis %>% 
  as.treedata() %>% 
  tree_subset(LCA_node, levels_back = 1)

colval_sub <- colval[names(colval) %in% tree_sub@data$Taxonomy]
tree_vis_sub <- save_tree(tree_sub, colval_sub, "tree_BCoAT_sub.pdf", 3, 3, 1.35, .78)
tree_vis_sub <- save_tree(tree_sub, colval_sub, "tree_BCoAT_sub.svg", 3, 3, 1.35, .78)
```

